variant = "loose"

[[issues]]
file = "src/Trait/ReflectionTrait.php"
code = "prefer-early-continue"
message = "Consider using early continue pattern to reduce nesting."
count = 1

[[issues]]
file = "tests/src/AbstractTestCase.php"
code = "no-redundant-method-override"
message = "Redundant method override."
count = 2

[[issues]]
file = "tests/src/Trait/ReflectionTraitTest.php"
code = "no-error-control-operator"
message = "Unsafe use of error control operator `@`."
count = 1

[[issues]]
file = "tests/src/Trait/ReflectionTraitTest.php"
code = "prefer-static-closure"
message = "This arrow function does not use `$this` and should be declared static."
count = 1

[[issues]]
file = "tests/src/Trait/ReflectionTraitTest.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1
